apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.mongo.labels.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.mongo.service.port }}
      targetPort: {{ .Values.mongo.service.targetPort }}
  clusterIP: {{ .Values.mongo.service.clusterIP }}
